---
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Copy website file
    copy:
      src: index.html
      dest: /var/www/html/index.html
